# Generated by Django 4.2.5 on 2023-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_des_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_des',
            field=models.CharField(max_length=500),
        ),
    ]
